# Generated by Django 5.0.1 on 2024-01-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='taxCode',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
